const Constants = {
   TYPE_SIGNAL_READY: 0,
   TYPE_SEARCH_FETCH: 1,
   TYPE_SEARCH_CONTEXT: 2,
   
   DEFAULT_DEF: 0,
   WIKIPEDIA_DEF: 1,
   OTHERS_DEF: 2,
   NOTES_DEF: 3,

   ACTION_WINDOW_RESIZE: 10,
   ACTION_JFRAME_RESIZE: 11,
   ACTION_JFRAME_MOVE: 12
}

export default Constants;