name: Release

on:
  workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18.x

    - name: Build files
      run: |
        npm ci
        npm run build

    - name: Upload build files
      uses: actions/upload-artifact@v3
      with:
        name: build
        path: /build/